### ISSUE TITLE
Missing Subtitles in Fullscreen (Chrome 73)

### ISSUE THREAD

**Issue by ronny1982** [weizhenye/ASS#18]
Chrome seems to have a new video player.
Subtitles are no longer shown when the video is switched to full-screen mode.

**Steps to reproduce:**
1. Download and install the latest Chrome browser (73+)
2. Start Chrome and open https://ass.js.org
3. Load the sample video and sample ASS file
4. Press play => subtitles are shown correctly
5. Switch the video to full-screen => subtitles no longer shown

**Comment by weizhenye** [comment]
See https://github.com/weizhenye/ASS/issues/2#issuecomment-271158016 and #9 , ass.js.org doesn't support subtitles in fullscreen, you should implement it yourself.

**Comment by Ever4engel** [comment]
The same isue occur in firefox 66.0.5 too
