### ISSUE TITLE
Font size is miscalculated because of line-height

### ISSUE THREAD

**Issue by kmamal** [weizhenye/ASS#21]
In function `getRealFontSize` you are creating an em-block (`<div>M</div>`) and measuring it's height to get a scaling factor. However the height of that block is affected by the CSS `line-height` property. In our application we set `line-height` to 1.5 and so all the subtitles appear smaller than they should be.

We have made a workaround by setting `line-height` to 1.2 in the container element. We think however that this is better done inside the `ASS-fix-font-size` class in your code.

**Comment by weizhenye** [comment]
line-height is not a specific value with different font-size and font-family, set it to 1.2 will cause more inconsistent.

**Comment by weizhenye** [comment]
Oh, I should set `line-height: normal;` inside ASS-fix-font-size

**Comment by kmamal** [comment]
@weizhenye Thanks for addressing this! You're right, `line-height: normal` is the correct approach.

But the problem is not completely solved: the lines of the subtitles themselves are displayed with the wrong line height. Could you also add `line-height: normal` to the subtitles themselves?
