### ISSUE TITLE
ass如何导入图片？

### ISSUE THREAD

**Issue by chenyangxx** [weizhenye/ASS#23]
看文档可以使用 Picture，但是Picture标签放入.ass文件，然后通过ffmpeg烧录.ass到视频，并不能展示图片

**Comment by weizhenye** [comment]
ASS 字幕格式规范最早是 Sub Station Alpha 软件制定的，它是支持文档描述的这些能力。当前 ASS 字幕渲染基本都是由 xy-VSFilter 和 libass 完成的，它们不支持 `[Picture]`。

**Comment by chenyangxx** [comment]
> ASS 字幕格式规范最早是 Sub Station Alpha 软件制定的，它是支持文档描述的这些能力。当前 ASS 字幕渲染基本都是由 xy-VSFilter 和 libass 完成的，它们不支持 `[Picture]`。

那请教一下，ASS如何才能支持外部导入图片？而不是通过内部的绘图标签

**Comment by weizhenye** [comment]
不支持。

当前 ASS 特效字幕有图形的，基本都是绘图标签绘制的。

有一些方案是将图片按像素一个点一个点绘制出来，会导致 ASS 文件很大，渲染很有问题。

**Comment by chenyangxx** [comment]
> 当前 ASS 特效字幕有图形的，基本都是绘图标签绘制的。

那 emoji 表情呢 ？ 囧

**Comment by weizhenye** [comment]
emoji 跟字体有关，一般字体支持成什么样就长什么样。

**Comment by chenyangxx** [comment]
> emoji 跟字体有关，一般字体支持成什么样就长什么样。

有个思路，可以把图片做成字体，打包成ttf，加载到ass

**Comment by weizhenye** [comment]
那一般也是矢量图才有好效果吧，~~都矢量图了不如直接绘图指令~~ 好像没什么转换的工具。

**Comment by chenyangxx** [comment]
[https://b23.tv/av83517821](url) 请问这种效果用是否可以用ass实现呢 😆

**Comment by weizhenye** [comment]
可以。我不会。

找个 http://www.tcax.org/ 之类的论坛混一个月应该就会了。

**Comment by chenyangxx** [comment]
> 可以。我不会。
> 
> 找个 http://www.tcax.org/ 之类的论坛混一个月应该就会了。

关键是上面的音符、小球之类的图片 如果绘制就麻烦了~
