### ISSUE TITLE
Demo don't works with fullscreen videos

### ISSUE THREAD

**Issue by LoganTann** [weizhenye/ASS#26]
everything is in the title !

**Comment by weizhenye** [comment]
https://github.com/weizhenye/ASS/issues/2#issuecomment-271158016

#9

#18

**Comment by LoganTann** [comment]
Ah, sorry
Forgot to read closed issues...

Maybe that's possible to add an option to this lib, to create a fullscreen div container with controls ?

**Comment by weizhenye** [comment]
No. Controls should be handled by video libraries like video.js, it's not a goal of ASS.js.

**Comment by LoganTann** [comment]
> 
> 
> No. Controls should be handled by video libraries like video.js, it's not a goal of ASS.js.
