### ISSUE TITLE
Some options to enable/disable features

### ISSUE THREAD

**Issue by eamanola** [weizhenye/ASS#28]
Feature request:
Some subs (see sample attached) take too long to render. Apart from obvious lag, sometimes browser asks, if user wants to wait or stop the website.

Maybe some flags/options to enable/disable certain tags?

[Shingeki no Kyojin NCOP.ass.txt](https://github.com/weizhenye/ASS/files/5716915/Shingeki.no.Kyojin.NCOP.ass.txt)

**Comment by weizhenye** [comment]
I'm working on changing CSS Animation to Web Animation API for animation on [next branch](https://github.com/weizhenye/ASS/tree/next), but it's still experimental.

You can try to build it yourself to check whether performance is better. Theoretically it should notably reduce the time of first load and renders more smoothly.

**Comment by eamanola** [comment]
got a dist/ass.js file? I could give it a go
