### ISSUE TITLE
Bug: viewBox="0 0 0 0" crash the page

### ISSUE THREAD

**Issue by everpcpc** [weizhenye/ASS#36]
ASS file with no `PlayerResX` and `PlayerResY` would result in svg `viewBox="0 0 0 0"` if using self created container, and subtitle not showing.
Furthermore, after setting `ScaledBorderAndShadow` to `yes`, browser crashes on the first cue.

**Comment by weizhenye** [comment]
https://github.com/weizhenye/ASS/blob/4e774850a1d660e6e12f40cb531b74e26c3c2eac/src/internal/init.js#L50-L53

Script resolution will be set to video resolution if there is no  `PlayResX` and `PlayResY`, it should not be resulting `viewBox="0 0 0 0"`, can you provide a sample ASS file?

**Comment by everpcpc** [comment]
[Dogville.2003.1080p.BluRay.H264.AAC-RARBG.zip](https://github.com/user-attachments/files/15774994/Dogville.2003.1080p.BluRay.H264.AAC-RARBG.zip)

**Comment by everpcpc** [comment]
> if using self created container

Maybe this is the difference?

**Comment by weizhenye** [comment]
After testing, container is not the reason.

Maybe it's because the video is still loading and the `loadedmetadata` event is not fired yet, so `video.videoWidth` is 0.
