### ISSUE TITLE
connect assjs with videojs

### ISSUE THREAD

**Issue by sandyAI** [weizhenye/ASS#4]
hello

how can i use assjs with videojs player?
is there an example ?

thanks

**Comment by weizhenye** [comment]
I'm not familiar with video.js and just followed the [quick start](https://github.com/videojs/video.js#quick-start) to make an rough example:

https://codepen.io/weizhenye/pen/YrgOJR

I may write a video.js plugin for ASS.js sometime.

**Comment by MorganDai** [comment]
![image](https://user-images.githubusercontent.com/62583049/87774284-eac8eb00-c856-11ea-9a9e-619ce83587d5.png)

Videojs Change the DOM. Just correct the `video` element id and container's id.
