### ISSUE TITLE
some video players change the width/height after new ASS(...)

### ISSUE THREAD

**Issue by orelHAnyvision** [weizhenye/ASS#45]
Hi
my app is running with vite and react
after loading the video its width/height changes only for external video platers like Plyr, ReactPlayer and so, for native video player it does work properly.
is there something I miss?

```
import Plyr from 'plyr-react'
...

 const handleLoad = () => {
    const videoElement = document.querySelector('video') 
    fetch(subs)
      .then((res) => res.text())
      .then((text) => {
        const ass = new ASS(
          text,
          videoElement
        )
      })
  }

...
return (
   <Plyr
                width={600}
                height={300}
                onLoadedData={handleLoad}
                source={{
                  type: 'video',
                  sources: [{ src: file }],
                }}
              />
)

```

**Comment by weizhenye** [comment]
If you don't provide container when initializing, ASS.js will create a container, and move the video to the container, it might be break player libs.

I suggest you to provide container and set styles yourself to make sure subtitles display in video's viewport.

```js
new ASS(content, video, { container: document.querySelector('.my-container') });
```
