### ISSUE TITLE
Error showing some Unicode charicters

### ISSUE THREAD

**Issue by yuygfgg** [weizhenye/ASS#47]
<img width="1006" alt="截屏2024-07-25 20 50 40" src="https://github.com/user-attachments/assets/6c510752-2eaf-4376-b1a6-6c7cc189f935">

[轻音少女.se2.ep21.ass.zip](https://github.com/user-attachments/files/16377905/se2.ep21.ass.zip)

**Comment by weizhenye** [comment]
It works fine in mine.

```ass
Style: Default,ZhunYuan,68,&H00FFFFFF,&HF0000000,&H00ED2AAC,&H78E645B0,-1,0,0,0,100,100,3,0,1,3.15,1.8,2,45,45,15,1
```
The `Default` Style use Fontname `ZhunYuan`, if this font is not installed in your computer, browser will fallback to sans-serif, ASS.js doesn't handle any font loading or rendering.

<img width="1471" alt="Screen Shot 2024-07-25 at 21 51 50" src="https://github.com/user-attachments/assets/39de2503-c83a-4bbc-aef5-e8e918b47a77">

You can open DevTools with F12 and uncheck the `font-family` to see if it's OK.

**Comment by yuygfgg** [comment]
> It works fine in mine.
> 
> ```
> Style: Default,ZhunYuan,68,&H00FFFFFF,&HF0000000,&H00ED2AAC,&H78E645B0,-1,0,0,0,100,100,3,0,1,3.15,1.8,2,45,45,15,1
> ```
> 
> The `Default` Style use Fontname `ZhunYuan`, if this font is not installed in your computer, browser will fallback to sans-serif, ASS.js doesn't handle any font loading or rendering.
> 
> <img alt="Screen Shot 2024-07-25 at 21 51 50" width="1471" src="https://private-user-images.githubusercontent.com/1879224/352133860-39de2503-c83a-4bbc-aef5-e8e918b47a77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5MTY0NTcsIm5iZiI6MTcyMTkxNjE1NywicGF0aCI6Ii8xODc5MjI0LzM1MjEzMzg2MC0zOWRlMjUwMy1jODNhLTRiYmMtYWVmNS1lOGU5MThiNDdhNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjVUMTQwMjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVjODJmNzBlZjNhYWQ3ZWMwOWMyYzM0YjVhMzYxZGZkOWY4YjU0MTRiMjBlOTBkZDVlYjMyNTE2N2JlNmJkMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Pv-bf1Ptu-A4iHsNvt8Sx83xROWZlsgd-8TbVLUP9Bs">
> You can open DevTools with F12 and uncheck the `font-family` to see if it's OK.

Unchecking font-family fixed my problem. But I got a question: 
Other software, including iina and infuse, shows ass subtitle correctly even without fonts required. As you mentioned, browser will fall back to sans-serif. Why didn't that work?

**Comment by weizhenye** [comment]
Is your system Linux?

Check `font-family` and try these:
* edit `font-family` value to `ZhunYuan`
* edit `font-family` value to `ZhunYuan, Arial, sans-serif`

Will any of these work?

**Comment by yuygfgg** [comment]
> * ZhunYuan

Well, none of these work. And I'm on macos.
<img width="1449" alt="截屏2024-07-25 22 37 27" src="https://github.com/user-attachments/assets/fd2669e2-c9ff-48b1-8d3d-609a1f316319">
<img width="1457" alt="截屏2024-07-25 22 40 10" src="https://github.com/user-attachments/assets/20be9a7c-5908-4251-84ff-171dddfd1340">

But I found that the following code works.

```html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>字体测试</title>
<style>
  .zhunyuan {
    font-family: ZhunYuan;
  }
  .arial {
    font-family: Arial;
  }
  .sans-serif {
    font-family: sans-serif;
  }
</style>
</head>
<body>
  <h1>字体测试</h1>
  <p class="zhunyuan">这是一段使用 ZhunYuan 字体的测试文本。</p>
  <p class="arial">这是一段使用 Arial 字体的测试文本。</p>
  <p class="sans-serif">这是一段使用 sans-serif 字体的测试文本。</p>
</body>
</html>
```
<img width="676" alt="截屏2024-07-25 22 38 43" src="https://github.com/user-attachments/assets/2b38324c-fb10-4500-b082-283d42f1c65d">

**Comment by yuygfgg** [comment]
Well, the problem seems to be solved by ** uninstalling ** the 2 ZhunYuan fonts. I don't know why. Maybe the 2 fonts are somehow broken?
<img width="1455" alt="截屏2024-07-25 22 48 16" src="https://github.com/user-attachments/assets/54662d6f-033e-4cc2-bd28-4e789c4965aa">

**Comment by weizhenye** [comment]
Do you install any ZhunYuan fonts before?

From my experience, after installing fonts, browser should be reopened to properly load the new font.

A possibility reason:
1. You installed a broken ZhunYuan before
2. `不太行…` doesn't show in ASS.js, or in any other pages
3. You installed a good ZhunYuan, but the ASS.js page is not reload, or the browser is not reopened, so it's not works
4. You open a test page, which browser already properly load it, so it works
5. You uninstalled all ZhunYuan fonts, so browser fallback to sans-serif and it works
