### ISSUE TITLE
加载不了ass.min.js

### ISSUE THREAD

**Issue by libsu** [weizhenye/ASS#5]
idea提示这段
fetch('/path/to/example.ass')
        .then(res => res.text())
    .then((text) => {
        const ass = new ASS(text, document.getElementById('video'));
    });
黄色，点开看了ass.min.js下 是乱的 ，另外demo页也用不了，望解答。（我npm了assjs）

**Comment by weizhenye** [comment]
如果你项目是有构建流程的话（如 webpack），可以 `import ASS from 'assjs';` 这样引入 `ASS` 变量。

如果是直接写在 HTML 页面里，可以这样引入 `<script src="https://cdn.jsdelivr.net/npm/assjs@0.0.2/dist/ass.min.js"></script>` 文件，在全局会有 `ASS` 变量。

README 里写的这段，是通过 [fetch](https://developer.mozilla.org/zh-CN/docs/Web/API/Fetch_API) 加载到 ass 字幕文件，如果不是现代浏览器，需要引入 [polyfill](https://github.com/github/fetch) 库。

demo 页面直接点 `load sample video` 和 `load sample ASS` 是可以运行的，你是什么浏览器？有报什么错吗？
