### ISSUE TITLE
Spacing lost between words when using \c

### ISSUE THREAD

**Issue by Thandden** [weizhenye/ASS#50]
![Screenshot from 2024-08-30 03-48-33](https://github.com/user-attachments/assets/7edcede4-0328-4469-bf25-53e18fa9282e)

`[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:02.00,Default,,0,0,0,,Twinkle {\c&H0000FF&}twinkle{\c} little star`

Spacing is lost between words when the \c parameter is used. Tested this on different .ASS parser and issue isn't there.

It should be:

`Twinkle twinkle little star`

Instead of:

`Twinkletwinklelittle star`

**Comment by weizhenye** [comment]
It will be fixed in `v0.1.2`. I'm doing a refactor of animation now, new release will be available when it's finished.

**Comment by Nicolab** [comment]
Same here, with the v0.1.2

Example: `Hello {\rHighlight}world{\rDefault} !`
Displayed `Helloworld!`

With others ASS parsers it's ok.
