### ISSUE TITLE
Question for max-width

### ISSUE THREAD

**Issue by RealTake** [weizhenye/ASS#52]
If there is no "effect", I'm not sure why you set max-width. Is there a problem that could happen when I remove that style?
Thankt you
![image](https://github.com/user-attachments/assets/4180501e-73f4-403f-b947-8c3c30d2dff7)

**Comment by weizhenye** [comment]
It's used for line wrap `\q`.

<img width="1529" alt="image" src="https://github.com/user-attachments/assets/92788681-d7a7-4ded-9b11-2f94c576c541">

<img width="1529" alt="image" src="https://github.com/user-attachments/assets/4119f0d0-80c6-49f6-9e28-d8da643f6127">
