### ISSUE TITLE
Spacing lost between words when using \styleName

### ISSUE THREAD

**Issue by Nicolab** [weizhenye/ASS#54]
Hello,

Related to the closed issue #50 
but with the v0.1.2

Example: `Hello {\rHighlight}world{\rDefault} !`
Displayed `Helloworld!`

With others ASS renderers is ok.

Hopefully it will be fixed, as this package is the one with the best rendering. 🙏

**Comment by Nicolab** [comment]
If that can help. When I change via the devTools `data-wrap-style="2"` to `0` or `3` the spaces are good.

**Comment by weizhenye** [comment]
Fixed in `0.1.3`

**Comment by Nicolab** [comment]
Great news, thanks!
I have tested and it's ok.
