### ISSUE TITLE
Incorrect ASS move effect speed

### ISSUE THREAD

**Issue by gonejack** [weizhenye/ASS#6]
I played a video and ass on https://ass.js.org, on the webpage, the ass danmaku moves incorrect slow.

The video and the ass are all right with IINA player on mac.

-material: https://www.dropbox.com/sh/9hot7ll920fu5qi/AAC5SSnrdlvOfJ3DL-iYNr5ma?dl=0
-latest mac os and chrome.

**Comment by weizhenye** [comment]
In `[Script Info]` section, `Timer` is set to `10.0000`, which is `100.0000` in general, that cause danmaku 10x slower.
IINA is using [libass](https://github.com/libass/libass) as its ASS renderer, libass seems ignores `Timer` directly.
It's not very clear how `Timer` behaves by spec, I'll check [xy-VSFilter](https://github.com/Cyberbeing/xy-VSFilter) later and follow its behavior.

**Comment by tiansh** [comment]
This ass file should works on VSFilter though it given incorrect `Timer`.
Not sure why.

**Comment by tiansh** [comment]
This ass file should works on VSFilter though it given incorrect `Timer`.
Not sure why.

**Comment by tiansh** [comment]
What is the preferred way to fix this in ass file? Change attribute value to 100.0000 or delete that line or anything else?

**Comment by weizhenye** [comment]
I tested it in xy-VSFilter and found it's also ignores `Timer`. So I'll ignore it in ASS.js too.

@tiansh I recommend you to change it to `100.0000`.
