### ISSUE TITLE
how to use ass.js?

### ISSUE THREAD

**Issue by dixyes** [weizhenye/ASS#8]
(or it's a bug?
use it like this: 

    <html>
    <head>
    <meta charset="utf-8">
    <title>rpr</title>
    </head>
    <body>
    <video style="height: 400px" id="video" src="/anime/2012_4/haiyore_nyaruko_san/[Yousei-raws]%20Haiyore!%20Nyaruko-san%2001%20[BDrip%201920x1080%20x264%20FLAC].mkv" autoplay ></video>

    <script src="https://cdn.jsdelivr.net/npm/assjs@0.0.6/dist/ass.min.js"></script>
    
    <script>
    fetch("/anime/2012_4/haiyore_nyaruko_san/[Yousei-raws]%20Haiyore!%20Nyaruko-san%2001%20[BDrip%201920x1080%20x264%20FLAC].sc.ass")
    .then(res => res.text())
    .then((text) => {
      window.ass = new ASS(text, document.getElementById("video"),);
      document.getElementById("video").play()
    });
    </script>
    </body>
    </html>

at Windows 10 1803, Chrome  67.0.3396.87 (64 bit)

what I got:
(no subtitle)
![http://c.hiphotos.baidu.com/image/%70%69%63/item/9358d109b3de9c8293e095486081800a18d8436b.jpg](http://c.hiphotos.baidu.com/image/%70%69%63/item/9358d109b3de9c8293e095486081800a18d8436b.jpg)

what i excpeted:
(at demo site)
![http://b.hiphotos.baidu.com/image/%70%69%63/item/b999a9014c086e06a4a0508c0e087bf40bd1cbe9.jpg](http://b.hiphotos.baidu.com/image/%70%69%63/item/b999a9014c086e06a4a0508c0e087bf40bd1cbe9.jpg)

(they are using exactly same file

**Comment by weizhenye** [comment]
```js
// ...
.then((text) => {
  window.ass = new ASS(text, document.getElementById("video"),);
  document.getElementById("video").play()
})
// add catch here
.catch(console.log);
```

You'll get following error:

> Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

You should always call `document.getElementById("video").play()` with user's operations.

**Comment by dixyes** [comment]
so I added "autoplay" to avoid call play()

now i try to use "controls" and click play button

the subtitle still wont appear

**Comment by weizhenye** [comment]
`autoplay` will not autoplay the video. Read https://goo.gl/xX8pDD for detail.

https://codepen.io/anon/pen/MBBbpZ

**Comment by dixyes** [comment]
i've found those ass files using UTF16BOM and http-server (npm http server i used) serve them as UTF8

when i chose them using browser they are fine, but with fetch() they are corrupt

but what‘s really strange is that ASSjs don't throw an exception....

困扰了我好久。。。
