### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by Linus789** [weizhenye/ASS#9]
Subtitles are hidden on fullscreen.
To prevent this, you have to override/rewrite the fullscreen method,
so the div will be fullscreen and not only the video.

**Comment by weizhenye** [comment]
https://github.com/weizhenye/ASS/issues/2#issuecomment-271158016

**Comment by Linus789** [comment]
So you have to use a library like video.js or overwrite the controls to solve this issue?

**Comment by weizhenye** [comment]
I think there is no way to support fullscreen from video. When clicking fullscreen button inside `<video>`, only `<video>` itself can be display on screen, any other elements is hidden.
You should write fullscreen button yourself, like many video libraries do.

**Comment by Linus789** [comment]
Okay, thanks.
